### ISSUE TITLE
Iterable does not work

### ISSUE THREAD

**Issue by SelAnt** [raydac/j-j-jvm#1]
Hi,
Excellent project. Unfortunately, following code fails on the cycle:

```
List<String> list = Collections.EMPTY_LIST;
for (String element: list) {
}
```
Output:
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer

	at com.igormaznitsa.jjjvm.JJJVMInterpreter._invoke(JJJVMInterpreter.java:1063)
	at com.igormaznitsa.jjjvm.JJJVMInterpreter.invoke(JJJVMInterpreter.java:77)
	at com.igormaznitsa.jjjvm.impl.JJJVMClassMethodImpl.invoke(JJJVMClassMethodImpl.java:111)
	

[iterable.zip](https://github.com/raydac/j-j-jvm/files/1704485/iterable.zip)

Could you please have a look?

**Comment by raydac** [comment]
your solution looks good enough so that I have approved your pull request, thanks a lot
