### ISSUE TITLE
Clone fails with java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by dave-griffiths** [raydac/j-j-jvm#9]
Hi, nice work with your interpreter! I was having problems with some code that clones an array so I added something to your test like this:
```
--- a/jdwp/java/src/test/java/com/igormaznitsa/jjjvm/JJJVMInterpreterTest.java
+++ b/jdwp/java/src/test/java/com/igormaznitsa/jjjvm/JJJVMInterpreterTest.java
@@ -2583,6 +2583,7 @@ public class JJJVMInterpreterTest extends TestHelper implements JSEProviderImpl.
                                 + " int index = 0;"
                                 + " for(int x=0; x<array.length; x++){"
                                 + "  int [] fill = array[x];"
+                                + "  int [] bill = (int [])fill.clone();"
                                 + "  for(int y=0; y< fill.length; y++){"
                                 + "    fill[y] = index++;"
                                 + "  }"
```
but that causes failures:
```
10:02:11.986 [main] ERROR com.igormaznitsa.jjjvm.JJJVMInterpreter - caught
java.lang.IllegalAccessException: Class com.igormaznitsa.jjjvm.impl.jse.JSEProviderImpl can not access a member of class java.lang.Object with modifiers "protected native"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[?:1.8.0-internal]
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296) ~[?:1.8.0-internal]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:491) ~[?:1.8.0-internal]
	at com.igormaznitsa.jjjvm.impl.jse.JSEProviderImpl.invoke(JSEProviderImpl.java:217) ~[classes/:?]
	at com.igormaznitsa.jjjvm.JJJVMInterpreter._invoke(JJJVMInterpreter.java:1516) [classes/:?]
	at com.igormaznitsa.jjjvm.JJJVMInterpreter.invoke(JJJVMInterpreter.java:81) [classes/:?]
	at com.igormaznitsa.jjjvm.utils.TestHelper.executeTestMethod(TestHelper.java:188) [test-classes/:?]
	at com.igormaznitsa.jjjvm.JJJVMInterpreterTest.testIntegration_FillMultidimensionalArray_Int(JJJVMInterpreterTest.java:2594) [test-classes/:?]
```
and
```
testIntegration_FillMultidimensionalArray_Int(com.igormaznitsa.jjjvm.JJJVMInterpreterTest)  Time elapsed: 0.905 sec  <<< ERROR!
java.lang.IllegalAccessException: Class com.igormaznitsa.jjjvm.impl.jse.JSEProviderImpl can not access a member of class java.lang.Object with modifiers "protected native"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.igormaznitsa.jjjvm.impl.jse.JSEProviderImpl.invoke(JSEProviderImpl.java:217)
	at com.igormaznitsa.jjjvm.JJJVMInterpreter._invoke(JJJVMInterpreter.java:1516)
	at com.igormaznitsa.jjjvm.JJJVMInterpreter.invoke(JJJVMInterpreter.java:81)
	at com.igormaznitsa.jjjvm.utils.TestHelper.executeTestMethod(TestHelper.java:188)
	at com.igormaznitsa.jjjvm.JJJVMInterpreterTest.testIntegration_FillMultidimensionalArray_Int(JJJVMInterpreterTest.java:2594)
```
How easy do you think that is to fix?

**Comment by raydac** [comment]
it is a bug, I made fix
